# Generated by Django 6.1.1 on 2026-09-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='direccion_entrega',
        ),
        migrations.AddField(
            model_name='pedido',
            name='calle',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_postal',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='colonia',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo contra entrega'), ('Transferencia', 'Transferencia Bancaria')], default='Efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_exterior',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='referencias',
            field=models.TextField(blank=True, help_text='Fachada, color de casa, etc.', null=True),
        ),
    ]
