# Generated by Django 6.1.1 on 2026-09-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_pedido_direccion_entrega_pedido_calle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_promocion',
            field=models.BooleanField(default=False, help_text='Mostrar en sección de Promociones'),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_popular',
            field=models.BooleanField(default=False, help_text='Mostrar en sección de Populares'),
        ),
    ]
