# Generated by Django 6.1.1 on 2026-09-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_producto_en_promocion_producto_es_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='latitud',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='longitud',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_comprador',
            field=models.CharField(default='', max_length=150),
        ),
    ]
