# Generated by Django 6.1.1 on 2026-09-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_pedido_latitud_pedido_longitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento_porcentaje',
            field=models.PositiveIntegerField(default=0, help_text='Ejemplo: 10 para 10% de descuento'),
        ),
    ]
